### ISSUE TITLE
yarn install fails due to dependency referencing "uberinternal.com" url

### ISSUE THREAD

**Issue by RwwL** [DianaSuvorova/rollup-react-app#1]
I just tried downloading the ZIP, navigating in, and running `yarn`. The result was:
```
yarn install v1.15.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://unpm.uberinternal.com/babel-plugin-transform-export-extensions/-/babel-plugin-transform-export-extensions-6.22.0.tgz: Request failed \"401 Unauthorized\"".
info If you think this is a bug, please open a bug report with the information provided in "/Users/rob/Desktop/rollup-react-app-master/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
Starting to look into it but thought I'd note the issue here first thing in case you've dealt with this before.

**Comment by RwwL** [comment]
Looks like everything builds if you use `npm i .`, though.

**Comment by RwwL** [comment]
...but running build after that install just gets me this:
```
> rollup-react-app@1.0.0 build /Users/rwwl/projects/rollup-react-app-master
> rollup -c rollup.config.js


src/index.js → dist/index.js...
(16): node_modules/react-dom/cjs/react-dom.development.js[BABEL] Note: The code generator has deoptimised the styling of "/Users/rwwl/projects/rollup-react-app-master/node_modules/react-dom/cjs/react-dom.development.js" as it exceeds the max of "500KB".
(35): commonjs-proxy-/Users/rwwl/projects/rollup-react-app-master/node_modules/object-assign/index.js[!] TypeError: Cannot use 'in' operator to search for 'value' in null
TypeError: Cannot use 'in' operator to search for 'value' in null
    at in (/Users/rwwl/projects/rollup-react-app-master/node_modules/rollup/dist/rollup.js:10099:46)
    at BinaryExpression.getLiteralValueAtPath (/Users/rwwl/projects/rollup-react-app-master/node_modules/rollup/dist/rollup.js:10119:16)
    at ConditionalExpression.getTestValue (/Users/rwwl/projects/rollup-react-app-master/node_modules/rollup/dist/rollup.js:10451:31)
    at ConditionalExpression.getReturnExpressionWhenCalledAtPath (/Users/rwwl/projects/rollup-react-app-master/node_modules/rollup/dist/rollup.js:10339:20)
    at LocalVariable.getReturnExpressionWhenCalledAtPath (/Users/rwwl/projects/rollup-react-app-master/node_modules/rollup/dist/rollup.js:2587:26)
    at Identifier$$1.getReturnExpressionWhenCalledAtPath (/Users/rwwl/projects/rollup-react-app-master/node_modules/rollup/dist/rollup.js:9621:34)
    at MemberExpression$$1.getReturnExpressionWhenCalledAtPath (/Users/rwwl/projects/rollup-react-app-master/node_modules/rollup/dist/rollup.js:11142:28)
    at CallExpression.bind (/Users/rwwl/projects/rollup-react-app-master/node_modules/rollup/dist/rollup.js:10180:49)
    at AssignmentExpression.NodeBase.bind (/Users/rwwl/projects/rollup-react-app-master/node_modules/rollup/dist/rollup.js:9106:23)
    at AssignmentExpression.bind (/Users/rwwl/projects/rollup-react-app-master/node_modules/rollup/dist/rollup.js:10029:31)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rollup-react-app@1.0.0 build: `rollup -c rollup.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rollup-react-app@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by RwwL** [comment]
OK, I get it, I needed to delete the `yarn.lock` to get the install to work. Unfortunately, the build doesn't work for me after that.
```
> rollup -c rollup.config.js
src/index.js → dist/index.js...
(12): node_modules/react-dom/cjs/react-dom.development.js[BABEL] Note: The code generator has deoptimised the styling of "/Users/rwwl/projects/rollup-react-app-master/node_modules/react-dom/cjs/react-dom.development.js" as it exceeds the max of "500KB".
(35): commonjs-proxy-/Users/rwwl/projects/rollup-react-app-master/node_modules/prop-types/lib/ReactPropTypesSecret.js[!] TypeError: Cannot use 'in' operator to search for 'value' in null
TypeError: Cannot use 'in' operator to search for 'value' in null
    at in (/Users/rwwl/projects/rollup-react-app-master/node_modules/rollup/dist/rollup.js:10099:46)
    at BinaryExpression.getLiteralValueAtPath (/Users/rwwl/projects/rollup-react-app-master/node_modules/rollup/dist/rollup.js:10119:16)
    at ConditionalExpression.getTestValue (/Users/rwwl/projects/rollup-react-app-master/node_modules/rollup/dist/rollup.js:10451:31)
    at ConditionalExpression.getReturnExpressionWhenCalledAtPath (/Users/rwwl/projects/rollup-react-app-master/node_modules/rollup/dist/rollup.js:10339:20)
    at LocalVariable.getReturnExpressionWhenCalledAtPath (/Users/rwwl/projects/rollup-react-app-master/node_modules/rollup/dist/rollup.js:2587:26)
    at Identifier$$1.getReturnExpressionWhenCalledAtPath (/Users/rwwl/projects/rollup-react-app-master/node_modules/rollup/dist/rollup.js:9621:34)
    at MemberExpression$$1.getReturnExpressionWhenCalledAtPath (/Users/rwwl/projects/rollup-react-app-master/node_modules/rollup/dist/rollup.js:11142:28)
    at CallExpression.bind (/Users/rwwl/projects/rollup-react-app-master/node_modules/rollup/dist/rollup.js:10180:49)
    at AssignmentExpression.NodeBase.bind (/Users/rwwl/projects/rollup-react-app-master/node_modules/rollup/dist/rollup.js:9106:23)
    at AssignmentExpression.bind (/Users/rwwl/projects/rollup-react-app-master/node_modules/rollup/dist/rollup.js:10029:31)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rollup-react-app@1.0.0 build: `rollup -c rollup.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rollup-react-app@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.```

**Comment by DianaSuvorova** [comment]
@RwwL thanks for the feedback, fixed reference to unpm registry in `yarn.lock`.
The next error you were getting is this one: https://github.com/rollup/rollup/issues/2342
Upgraded rollup in the same PR.

Should work now. Thanks for giving it a try!
